### ISSUE TITLE
Liouville

### ISSUE THREAD

**Issue by gharib85** [tomfay/heom-lab#1]
L_sys = -1.0i*(kron(H_sys,id_sys) - kron(id_sys,transpose(H_sys))) ;

Why use transpose?

**Comment by tomfay** [comment]
This is the standard way of constructing the matrix representation of the super operator _A__R rho =  rho  A. See appendix C.3 of this for an explanation: https://ora.ox.ac.uk/objects/uuid:f5878b88-c5ba-4cbd-83af-857431aef66e
