### ISSUE TITLE
getBathInformationAB.m

### ISSUE THREAD

**Issue by gharib85** [tomfay/heom-lab#2]
I noticed in function Folder 
Many function ended with A B
I never dealt with this kind of implementation 
Please I need some explanation and I will be thankful if you provide me with some references for that

**Comment by tomfay** [comment]
Hi. This is an in development method. It's not complete, or tested, or published, and I don't know if it works. If you're interested in using the code I'd use the scripts in the "examples" folder, as these have been fairly thoroughly tested.
